# Port
server:
  port: 9191

spring:
  application:
      name: API-GATEWAY
  cloud:
    gateway:
      routes:
        - id: AUTORIZACIONAPUESTAS-SERVICE
          uri: lb://AUTORIZACIONAPUESTAS-SERVICE
          predicates:
            - Path=/autorizacionapuestas/**
          filters:
            - name: CircuitBreaker
              args:
                name: AUTORIZACIONAPUESTAS-SERVICE
                fallbackuri: forward:/autorizacionapuestasServiceFallBack
        - id: TICKET-SERVICE
          uri: lb://TICKET-SERVICE
          predicates:
            - Path=/tickets/**
          filters:
            - name: CircuitBreaker
              args:
                name: TICKET-SERVICEE
                fallbackuri: forward:/ticketServiceFallBack  

hystrix:
  command:
    fallbackcmd:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 4000
            
management:
  endpoints:
    web:
      exposure:
        include: '*'
        
# Eureka Server
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
        defaultZone: http://localhost:8761/eureka/
  instance:
      hostname: localhost
