server:
    port: 9002

spring:
# Database
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/test_db
    username: root
    password: root

# Eureka Server
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true  
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
      
